version: "3.4"
services:
  zoneminder:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: masterblaster
    ports:
      - 8443:443
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
    cap_add:
      - NET_ADMIN
    container_name: zoneminder
    environment:
      - PGID=99
      - PUID=100
      - TZ=America/New_York
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    logging:
      driver: json-file
      options:
        max-file: 10
        max-size: 200k
    restart: unless-stopped
    shm_size: "8gb"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /DockerConfig/containers/shared:/shared
      - /media/Public:/storage
      - ./zoneminder/config:/config
      - ./zoneminder/data:/var/cache/zoneminder
